import { useQuery, useMutation } from "@tanstack/react-query";
import { useAuth } from "./use-auth";
import { queryClient, apiRequest } from "@/lib/queryClient";

interface Entry {
  id: string;
  date: string;
  net: number;
  betAmount: number;
  winningAmount: number;
  notes?: string;
}

interface CapitalInjection {
  id: string;
  date: string;
  amount: number;
  notes?: string;
  autoGenerated?: boolean;
}

interface UserSettings {
  baseline: number;
  weekStartDate: string;
}

const STORAGE_KEY = "bt.entries.v1";
const INJECTIONS_KEY = "bt.injections.v7";
const BASELINE_KEY = "bt.baseline.v1";

export function useDataStorage() {
  const { isAuthenticated, user } = useAuth();

  // Check subscription status (for future premium features, not for cloud storage)
  const { data: subscriptionData } = useQuery({
    queryKey: ['/api/subscription-status'],
    enabled: !!user,
  });

  const hasActiveSubscription = (subscriptionData as any)?.hasActiveSubscription || false;
  // Cloud storage is now available to ALL authenticated users
  const useCloudStorage = isAuthenticated;

  // Betting entries
  const { data: dbEntries } = useQuery<Entry[]>({
    queryKey: ['/api/betting-entries'],
    enabled: useCloudStorage,
  });

  const createEntryMutation = useMutation({
    mutationFn: async (entry: Omit<Entry, 'id'>) => {
      return await apiRequest('POST', '/api/betting-entries', entry);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/betting-entries'] });
    },
  });

  const deleteEntryMutation = useMutation({
    mutationFn: async (id: string) => {
      return await apiRequest('DELETE', `/api/betting-entries/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/betting-entries'] });
    },
  });

  const deleteAllEntriesMutation = useMutation({
    mutationFn: async () => {
      return await apiRequest('DELETE', '/api/betting-entries');
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/betting-entries'] });
    },
  });

  // Capital injections
  const { data: dbInjections } = useQuery<CapitalInjection[]>({
    queryKey: ['/api/capital-injections'],
    enabled: useCloudStorage,
  });

  const createInjectionMutation = useMutation({
    mutationFn: async (injection: Omit<CapitalInjection, 'id'>) => {
      return await apiRequest('POST', '/api/capital-injections', injection);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/capital-injections'] });
    },
  });

  const deleteInjectionMutation = useMutation({
    mutationFn: async (id: string) => {
      return await apiRequest('DELETE', `/api/capital-injections/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/capital-injections'] });
    },
  });

  const deleteAllInjectionsMutation = useMutation({
    mutationFn: async () => {
      return await apiRequest('DELETE', '/api/capital-injections');
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/capital-injections'] });
    },
  });

  // Settings
  const { data: dbSettings } = useQuery<UserSettings>({
    queryKey: ['/api/settings'],
    enabled: useCloudStorage,
    retry: false,
  });

  const createSettingsMutation = useMutation({
    mutationFn: async (settings: UserSettings) => {
      return await apiRequest('POST', '/api/settings', settings);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/settings'] });
    },
  });

  const updateSettingsMutation = useMutation({
    mutationFn: async (settings: Partial<UserSettings>) => {
      return await apiRequest('PATCH', '/api/settings', settings);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/settings'] });
    },
  });

  // Migration function
  const migrateMutation = useMutation({
    mutationFn: async () => {
      if (!isAuthenticated) return;

      // Get localStorage data
      const localEntries = localStorage.getItem(STORAGE_KEY);
      const localInjections = localStorage.getItem(INJECTIONS_KEY);
      const localBaseline = localStorage.getItem(BASELINE_KEY);

      const migrationPromises = [];

      // Migrate entries
      if (localEntries) {
        const entries: Entry[] = JSON.parse(localEntries);
        for (const entry of entries) {
          const { id, ...entryData } = entry;
          migrationPromises.push(
            apiRequest('POST', '/api/betting-entries', entryData)
          );
        }
      }

      // Migrate injections
      if (localInjections) {
        const injections: CapitalInjection[] = JSON.parse(localInjections);
        for (const injection of injections) {
          const { id, ...injectionData } = injection;
          migrationPromises.push(
            apiRequest('POST', '/api/capital-injections', injectionData)
          );
        }
      }

      // Migrate settings
      if (localBaseline) {
        const baseline = JSON.parse(localBaseline);
        migrationPromises.push(
          apiRequest('POST', '/api/settings', {
            baseline,
            weekStartDate: new Date().toISOString().split('T')[0],
          })
        );
      }

      await Promise.all(migrationPromises);

      // Clear localStorage after successful migration
      localStorage.removeItem(STORAGE_KEY);
      localStorage.removeItem(INJECTIONS_KEY);
      localStorage.removeItem(BASELINE_KEY);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/betting-entries'] });
      queryClient.invalidateQueries({ queryKey: ['/api/capital-injections'] });
      queryClient.invalidateQueries({ queryKey: ['/api/settings'] });
    },
  });

  return {
    isAuthenticated,
    user,
    hasActiveSubscription,
    useCloudStorage,
    entries: useCloudStorage ? (dbEntries || []) : null,
    injections: useCloudStorage ? (dbInjections || []) : null,
    settings: useCloudStorage ? dbSettings : null,
    createEntry: createEntryMutation.mutateAsync,
    deleteEntry: deleteEntryMutation.mutateAsync,
    deleteAllEntries: deleteAllEntriesMutation.mutateAsync,
    createInjection: createInjectionMutation.mutateAsync,
    deleteInjection: deleteInjectionMutation.mutateAsync,
    deleteAllInjections: deleteAllInjectionsMutation.mutateAsync,
    createSettings: createSettingsMutation.mutateAsync,
    updateSettings: updateSettingsMutation.mutateAsync,
    migrateLocalData: migrateMutation.mutateAsync,
    isMigrating: migrateMutation.isPending,
  };
}
