import { z } from "zod";

// User schemas for MongoDB
export const userSchema = z.object({
  _id: z.string(),
  username: z.string(),
  password: z.string(),
  email: z.string().email(),
  createdAt: z.date(),
  stripeCustomerId: z.string().nullable().optional(),
  stripeSubscriptionId: z.string().nullable().optional(),
  premiumOverride: z.boolean().optional(), // Admin-granted premium access
});

export const insertUserSchema = z.object({
  username: z.string().min(3, "Username must be at least 3 characters"),
  password: z.string().min(6, "Password must be at least 6 characters"),
  email: z.string().email("Please enter a valid email address"),
});

// Email is not included - it's unchangeable after signup
export const updateUserSchema = z.object({
  username: z.string().min(3).optional(),
  password: z.string().min(6).optional(),
});

export type User = z.infer<typeof userSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type UpdateUser = z.infer<typeof updateUserSchema>;

// Tip expense schemas for MongoDB
export const tipExpenseSchema = z.object({
  _id: z.string(),
  date: z.string(),
  amount: z.string(),
  provider: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export const insertTipExpenseSchema = z.object({
  date: z.string(),
  amount: z.string(),
  provider: z.string().optional(),
  notes: z.string().optional(),
});

export type TipExpense = z.infer<typeof tipExpenseSchema>;
export type InsertTipExpense = z.infer<typeof insertTipExpenseSchema>;

// Bet category options
export const SPORTS = ['NFL', 'NBA', 'MLB', 'NHL', 'Soccer', 'Tennis', 'Golf', 'MMA/UFC', 'Boxing', 'College Football', 'College Basketball', 'Other'] as const;
export const BET_TYPES = ['Moneyline', 'Spread', 'Over/Under', 'Parlay', 'Prop', 'Futures', 'Live Bet', 'Teaser', 'Other'] as const;

export type Sport = typeof SPORTS[number];
export type BetType = typeof BET_TYPES[number];

// Betting entry schemas for MongoDB
export const bettingEntrySchema = z.object({
  _id: z.string(),
  userId: z.string(),
  date: z.string(),
  net: z.number(),
  betAmount: z.number(),
  winningAmount: z.number(),
  notes: z.string().optional(),
  bankrollId: z.string().optional(), // For multiple bankrolls feature
  // Category fields
  sport: z.string().optional(),
  league: z.string().optional(),
  betType: z.string().optional(),
});

export const insertBettingEntrySchema = z.object({
  date: z.string(),
  net: z.number(),
  betAmount: z.number(),
  winningAmount: z.number(),
  notes: z.string().optional(),
  bankrollId: z.string().optional(),
  // Category fields
  sport: z.string().optional(),
  league: z.string().optional(),
  betType: z.string().optional(),
});

export type BettingEntry = z.infer<typeof bettingEntrySchema>;
export type InsertBettingEntry = z.infer<typeof insertBettingEntrySchema>;

// Capital injection schemas for MongoDB
export const capitalInjectionSchema = z.object({
  _id: z.string(),
  userId: z.string(),
  date: z.string(),
  amount: z.number(),
  notes: z.string().optional(),
  autoGenerated: z.boolean().optional(),
});

export const insertCapitalInjectionSchema = z.object({
  date: z.string(),
  amount: z.number(),
  notes: z.string().optional(),
  autoGenerated: z.boolean().optional(),
});

export type CapitalInjection = z.infer<typeof capitalInjectionSchema>;
export type InsertCapitalInjection = z.infer<typeof insertCapitalInjectionSchema>;

// User settings schema for MongoDB
export const userSettingsSchema = z.object({
  _id: z.string(),
  userId: z.string(),
  baseline: z.number(),
  weekStartDate: z.string(),
});

export const insertUserSettingsSchema = z.object({
  baseline: z.number(),
  weekStartDate: z.string(),
});

export const updateUserSettingsSchema = z.object({
  baseline: z.number().optional(),
  weekStartDate: z.string().optional(),
});

export type UserSettings = z.infer<typeof userSettingsSchema>;
export type InsertUserSettings = z.infer<typeof insertUserSettingsSchema>;
export type UpdateUserSettings = z.infer<typeof updateUserSettingsSchema>;

// Bankroll schemas for Multiple Bankrolls feature
export const bankrollSchema = z.object({
  _id: z.string(),
  userId: z.string(),
  name: z.string(),
  color: z.string(),
  description: z.string().optional(),
  baseline: z.number(),
  isDefault: z.boolean().optional(),
  createdAt: z.date(),
});

export const insertBankrollSchema = z.object({
  name: z.string().min(1, "Bankroll name is required"),
  color: z.string(),
  description: z.string().optional(),
  baseline: z.number(),
  isDefault: z.boolean().optional(),
});

export const updateBankrollSchema = z.object({
  name: z.string().min(1).optional(),
  color: z.string().optional(),
  description: z.string().optional(),
  baseline: z.number().optional(),
  isDefault: z.boolean().optional(),
});

export type Bankroll = z.infer<typeof bankrollSchema>;
export type InsertBankroll = z.infer<typeof insertBankrollSchema>;
export type UpdateBankroll = z.infer<typeof updateBankrollSchema>;
