import { z } from "zod";

// User schemas for MongoDB
export const userSchema = z.object({
  _id: z.string(),
  username: z.string(),
  password: z.string(),
  email: z.string().email(),
  createdAt: z.date(),
});

export const insertUserSchema = z.object({
  username: z.string().min(3, "Username must be at least 3 characters"),
  password: z.string().min(6, "Password must be at least 6 characters"),
  email: z.string().email("Please enter a valid email address"),
});

// Email is not included - it's unchangeable after signup
export const updateUserSchema = z.object({
  username: z.string().min(3).optional(),
  password: z.string().min(6).optional(),
});

export type User = z.infer<typeof userSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type UpdateUser = z.infer<typeof updateUserSchema>;

// Tip expense schemas for MongoDB
export const tipExpenseSchema = z.object({
  _id: z.string(),
  date: z.string(),
  amount: z.string(),
  provider: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export const insertTipExpenseSchema = z.object({
  date: z.string(),
  amount: z.string(),
  provider: z.string().optional(),
  notes: z.string().optional(),
});

export type TipExpense = z.infer<typeof tipExpenseSchema>;
export type InsertTipExpense = z.infer<typeof insertTipExpenseSchema>;

// Betting entry schemas for MongoDB
export const bettingEntrySchema = z.object({
  _id: z.string(),
  userId: z.string(),
  date: z.string(),
  net: z.number(),
  betAmount: z.number(),
  winningAmount: z.number(),
  notes: z.string().optional(),
});

export const insertBettingEntrySchema = z.object({
  date: z.string(),
  net: z.number(),
  betAmount: z.number(),
  winningAmount: z.number(),
  notes: z.string().optional(),
});

export type BettingEntry = z.infer<typeof bettingEntrySchema>;
export type InsertBettingEntry = z.infer<typeof insertBettingEntrySchema>;

// Capital injection schemas for MongoDB
export const capitalInjectionSchema = z.object({
  _id: z.string(),
  userId: z.string(),
  date: z.string(),
  amount: z.number(),
  notes: z.string().optional(),
  autoGenerated: z.boolean().optional(),
});

export const insertCapitalInjectionSchema = z.object({
  date: z.string(),
  amount: z.number(),
  notes: z.string().optional(),
  autoGenerated: z.boolean().optional(),
});

export type CapitalInjection = z.infer<typeof capitalInjectionSchema>;
export type InsertCapitalInjection = z.infer<typeof insertCapitalInjectionSchema>;

// User settings schema for MongoDB
export const userSettingsSchema = z.object({
  _id: z.string(),
  userId: z.string(),
  baseline: z.number(),
  weekStartDate: z.string(),
});

export const insertUserSettingsSchema = z.object({
  baseline: z.number(),
  weekStartDate: z.string(),
});

export const updateUserSettingsSchema = z.object({
  baseline: z.number().optional(),
  weekStartDate: z.string().optional(),
});

export type UserSettings = z.infer<typeof userSettingsSchema>;
export type InsertUserSettings = z.infer<typeof insertUserSettingsSchema>;
export type UpdateUserSettings = z.infer<typeof updateUserSettingsSchema>;
