import { useState, useEffect, useMemo } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
	Pencil,
	Trash2,
	Wallet,
	ChevronLeft,
	ChevronRight,
	ArrowUpDown,
	ArrowUp,
	ArrowDown,
} from 'lucide-react';
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from '@/components/ui/table';
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select';

interface CapitalInjection {
	id: string;
	date: string;
	amount: number;
	notes?: string;
	autoGenerated?: boolean;
}

interface CapitalInjectionsTableProps {
	capitalInjections: CapitalInjection[];
	onEdit: (id: string) => void;
	onDelete: (id: string) => void;
	onAddDeposit: () => void;
}

export default function CapitalInjectionsTable({
	capitalInjections,
	onEdit,
	onDelete,
	onAddDeposit,
}: CapitalInjectionsTableProps) {
	const [currentPage, setCurrentPage] = useState(1);
	const [itemsPerPage, setItemsPerPage] = useState(10);

	// Sort state
	type SortColumn = 'date' | 'amount';
	const [sortColumn, setSortColumn] = useState<SortColumn>('date');
	const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');

	// Filter out auto-generated injections - only show manual deposits
	const manualInjections = useMemo(() => {
		return capitalInjections.filter((inj) => !inj.autoGenerated);
	}, [capitalInjections]);

	// Sort injections
	const sortedInjections = useMemo(() => {
		return [...manualInjections].sort((a, b) => {
			let comparison = 0;

			switch (sortColumn) {
				case 'date':
					comparison =
						new Date(a.date).getTime() - new Date(b.date).getTime();
					break;
				case 'amount':
					comparison = a.amount - b.amount;
					break;
			}

			return sortDirection === 'asc' ? comparison : -comparison;
		});
	}, [manualInjections, sortColumn, sortDirection]);

	// Toggle sort for a column
	const handleSort = (column: SortColumn) => {
		if (sortColumn === column) {
			setSortDirection((prev) => (prev === 'asc' ? 'desc' : 'asc'));
		} else {
			setSortColumn(column);
			setSortDirection('desc');
		}
		setCurrentPage(1);
	};

	// Get sort icon for a column
	const SortIcon = ({ column }: { column: SortColumn }) => {
		if (sortColumn !== column) {
			return <ArrowUpDown className='w-4 h-4 ml-1 opacity-50' />;
		}
		return sortDirection === 'asc' ? (
			<ArrowUp className='w-4 h-4 ml-1' />
		) : (
			<ArrowDown className='w-4 h-4 ml-1' />
		);
	};

	useEffect(() => {
		const totalPages = Math.ceil(sortedInjections.length / itemsPerPage);
		if (currentPage > totalPages && totalPages > 0) {
			setCurrentPage(totalPages);
		}
	}, [sortedInjections.length, itemsPerPage, currentPage]);

	const formatDate = (dateString: string) => {
		const date = new Date(dateString);
		return date.toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric',
		});
	};

	const totalDeposits = manualInjections.reduce(
		(sum, inj) => sum + inj.amount,
		0
	);

	if (manualInjections.length === 0) {
		return (
			<Card className='p-8 text-center'>
				<p className='text-muted-foreground'>
					No cash deposits yet. Add your first deposit to track
					additional funds!
				</p>
			</Card>
		);
	}

	const totalPages = Math.ceil(sortedInjections.length / itemsPerPage);
	const startIndex = (currentPage - 1) * itemsPerPage;
	const endIndex = startIndex + itemsPerPage;
	const paginatedInjections = sortedInjections.slice(startIndex, endIndex);

	const handlePageChange = (newPage: number) => {
		setCurrentPage(newPage);
	};

	const handleItemsPerPageChange = (value: string) => {
		setItemsPerPage(Number(value));
		setCurrentPage(1);
	};

	return (
		<Card className='p-3 sm:p-4 lg:p-6'>
			<div className='flex justify-between items-center mb-3 sm:mb-4'>
				<div>
					<h2 className='text-base sm:text-lg font-semibold'>
						Cash Deposits
					</h2>
					<p className='text-xs text-muted-foreground'>
						Total: ${totalDeposits.toLocaleString()}
					</p>
				</div>
				<Button
					onClick={onAddDeposit}
					size='sm'
					data-testid='button-add-deposit-table'>
					<Wallet className='w-4 h-4 mr-2' />
					Add Deposit
				</Button>
			</div>

			{/* Mobile Sort Control */}
			<div className='sm:hidden flex items-center gap-2 mb-3'>
				<span className='text-xs text-muted-foreground'>Sort:</span>
				<Select
					value={`${sortColumn}-${sortDirection}`}
					onValueChange={(value) => {
						const [col, dir] = value.split('-') as [
							SortColumn,
							'asc' | 'desc'
						];
						setSortColumn(col);
						setSortDirection(dir);
						setCurrentPage(1);
					}}>
					<SelectTrigger className='flex-1 h-8 text-xs'>
						<SelectValue />
					</SelectTrigger>
					<SelectContent>
						<SelectItem value='date-desc'>Date (Newest)</SelectItem>
						<SelectItem value='date-asc'>Date (Oldest)</SelectItem>
						<SelectItem value='amount-desc'>
							Amount (Highest)
						</SelectItem>
						<SelectItem value='amount-asc'>
							Amount (Lowest)
						</SelectItem>
					</SelectContent>
				</Select>
			</div>

			{/* Mobile Card Layout */}
			<div className='sm:hidden space-y-3'>
				{paginatedInjections.map((injection) => (
					<Card
						key={injection.id}
						className='p-3'
						data-testid={`row-injection-${injection.id}`}>
						<div className='flex justify-between items-start mb-2'>
							<span className='text-sm font-medium'>
								{formatDate(injection.date)}
							</span>
							<div className='flex gap-1'>
								<Button
									size='icon'
									variant='ghost'
									onClick={() => onEdit(injection.id)}
									data-testid={`button-edit-injection-mobile-${injection.id}`}>
									<Pencil className='w-4 h-4' />
								</Button>
								<Button
									size='icon'
									variant='ghost'
									onClick={() => onDelete(injection.id)}
									data-testid={`button-delete-injection-mobile-${injection.id}`}>
									<Trash2 className='w-4 h-4 text-destructive' />
								</Button>
							</div>
						</div>
						<div className='space-y-2'>
							<div>
								<p className='text-xs text-muted-foreground mb-0.5'>
									Amount
								</p>
								<p
									className='text-lg font-bold font-mono text-profit'
									data-testid={`text-amount-mobile-${injection.id}`}>
									+${injection.amount.toLocaleString()}
								</p>
							</div>
							{injection.notes && (
								<p className='text-sm text-muted-foreground italic'>
									{injection.notes}
								</p>
							)}
						</div>
					</Card>
				))}
			</div>

			{/* Desktop Table Layout */}
			<div className='hidden sm:block overflow-x-auto'>
				<Table>
					<TableHeader>
						<TableRow>
							<TableHead>
								<button
									onClick={() => handleSort('date')}
									className='flex items-center hover:text-foreground transition-colors'>
									Date
									<SortIcon column='date' />
								</button>
							</TableHead>
							<TableHead>
								<button
									onClick={() => handleSort('amount')}
									className='flex items-center hover:text-foreground transition-colors'>
									Amount
									<SortIcon column='amount' />
								</button>
							</TableHead>
							<TableHead className='hidden lg:table-cell'>
								Notes
							</TableHead>
							<TableHead className='text-right'>
								Actions
							</TableHead>
						</TableRow>
					</TableHeader>
					<TableBody>
						{paginatedInjections.map((injection) => (
							<TableRow
								key={injection.id}
								data-testid={`row-injection-${injection.id}`}>
								<TableCell className='font-medium'>
									{formatDate(injection.date)}
								</TableCell>
								<TableCell>
									<span
										className='font-mono font-semibold text-profit'
										data-testid={`text-amount-${injection.id}`}>
										+${injection.amount.toLocaleString()}
									</span>
								</TableCell>
								<TableCell className='hidden lg:table-cell text-muted-foreground max-w-xs truncate'>
									{injection.notes || '—'}
								</TableCell>
								<TableCell className='text-right'>
									<div className='flex justify-end gap-2'>
										<Button
											size='icon'
											variant='ghost'
											onClick={() => onEdit(injection.id)}
											data-testid={`button-edit-injection-${injection.id}`}>
											<Pencil className='w-4 h-4' />
										</Button>
										<Button
											size='icon'
											variant='ghost'
											onClick={() =>
												onDelete(injection.id)
											}
											data-testid={`button-delete-injection-${injection.id}`}>
											<Trash2 className='w-4 h-4 text-destructive' />
										</Button>
									</div>
								</TableCell>
							</TableRow>
						))}
					</TableBody>
				</Table>
			</div>

			{/* Pagination Controls */}
			<div className='flex flex-col sm:flex-row items-center justify-between gap-3 mt-4 pt-4 border-t'>
				<div className='flex items-center gap-2'>
					<span className='text-sm text-muted-foreground'>
						Rows per page:
					</span>
					<Select
						value={String(itemsPerPage)}
						onValueChange={handleItemsPerPageChange}>
						<SelectTrigger
							className='w-20'
							data-testid='select-deposits-per-page'>
							<SelectValue />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value='10'>10</SelectItem>
							<SelectItem value='25'>25</SelectItem>
							<SelectItem value='50'>50</SelectItem>
							<SelectItem value='100'>100</SelectItem>
						</SelectContent>
					</Select>
				</div>
				<div className='flex items-center gap-2'>
					<span className='text-sm text-muted-foreground'>
						Page {currentPage} of {totalPages} (
						{sortedInjections.length} deposits)
					</span>
					<div className='flex gap-1'>
						<Button
							variant='outline'
							size='icon'
							onClick={() => handlePageChange(currentPage - 1)}
							disabled={currentPage === 1}
							data-testid='button-prev-deposit-page'
							aria-label='Previous page'>
							<ChevronLeft className='h-4 w-4' />
						</Button>
						<Button
							variant='outline'
							size='icon'
							onClick={() => handlePageChange(currentPage + 1)}
							disabled={currentPage === totalPages}
							data-testid='button-next-deposit-page'
							aria-label='Next page'>
							<ChevronRight className='h-4 w-4' />
						</Button>
					</div>
				</div>
			</div>
		</Card>
	);
}
