import { useState, useEffect } from 'react';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Calculator, TrendingUp, AlertCircle } from 'lucide-react';
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select';

interface Entry {
	id: string;
	date: string;
	net: number;
	betAmount: number;
	winningAmount: number;
	notes?: string;
}

interface TipExpense {
	id: string;
	date: string;
	amount: number;
	provider?: string;
	notes?: string;
}

interface CapitalInjection {
	id: string;
	date: string;
	amount: number;
	notes?: string;
	autoGenerated?: boolean;
}

interface ProfitCalculatorProps {
	entries: Entry[];
	tipExpenses: TipExpense[];
	baseline: number | null;
	capitalInjections: CapitalInjection[];
}

const CALC_STORAGE_KEY = 'bt.profitCalc.v1';

interface CalculatorSettings {
	weeklyProfitGoal: number;
	tipPricingType: 'weekly' | 'per-bet';
	weeklyPackagePrice: number;
	perBetTipPrice: number;
	estimatedBetsPerWeek: number;
	weekStartDate: string;
	profitPercentPerWin: number; // e.g., 90 for -110 odds, 100 for +100 odds
}

export default function ProfitCalculator({
	entries,
	tipExpenses,
	baseline,
	capitalInjections,
}: ProfitCalculatorProps) {
	const today = new Date().toISOString().split('T')[0];

	const [settings, setSettings] = useState<CalculatorSettings>({
		weeklyProfitGoal: 500,
		tipPricingType: 'weekly',
		weeklyPackagePrice: 100,
		perBetTipPrice: 10,
		estimatedBetsPerWeek: 10,
		weekStartDate: today,
		profitPercentPerWin: 90, // Default for -110 odds
	});

	useEffect(() => {
		const stored = localStorage.getItem(CALC_STORAGE_KEY);
		if (stored) {
			try {
				const parsed = JSON.parse(stored);
				setSettings({
					weeklyProfitGoal: parsed.weeklyProfitGoal ?? 500,
					tipPricingType: parsed.tipPricingType ?? 'weekly',
					weeklyPackagePrice: parsed.weeklyPackagePrice ?? 100,
					perBetTipPrice: parsed.perBetTipPrice ?? 10,
					estimatedBetsPerWeek: parsed.estimatedBetsPerWeek ?? 10,
					weekStartDate: parsed.weekStartDate || today,
					profitPercentPerWin: parsed.profitPercentPerWin ?? 90,
				});
			} catch (e) {
				console.error('Failed to load calculator settings:', e);
			}
		}
	}, []);

	useEffect(() => {
		localStorage.setItem(CALC_STORAGE_KEY, JSON.stringify(settings));
	}, [settings]);

	// Helper to parse date string in local timezone (avoids UTC offset issues)
	const parseLocalDate = (dateStr: string) => {
		if (!dateStr) return new Date(); // Fallback to today if empty
		const [year, month, day] = dateStr.split('-').map(Number);
		if (!year || !month || !day) return new Date(); // Fallback to today if malformed
		return new Date(year, month - 1, day, 0, 0, 0, 0);
	};

	const isInCurrentWeek = (dateStr: string) => {
		const weekStart = parseLocalDate(settings.weekStartDate);
		const weekEnd = new Date(weekStart);
		weekEnd.setDate(weekEnd.getDate() + 7);

		// Extract date-only portion (YYYY-MM-DD) from various formats
		// Handles: "2025-09-30T15:47", "2025-09-30T15:47Z", "2025-09-30 15:47"
		const datePortion = dateStr.includes('T')
			? dateStr.split('T')[0]
			: dateStr.split(' ')[0];

		// Parse and validate the date portion
		const [year, month, day] = datePortion.split('-').map(Number);
		if (!year || !month || !day) {
			console.warn('Invalid date format for week calculation:', dateStr);
			return false; // Exclude invalid dates from week
		}

		const checkDate = new Date(year, month - 1, day, 0, 0, 0, 0);
		return checkDate >= weekStart && checkDate < weekEnd;
	};

	const getCurrentWeekEntries = () => {
		return entries.filter((entry) => isInCurrentWeek(entry.date));
	};

	const getCurrentWeekTipExpenses = () => {
		return tipExpenses.filter((expense) => isInCurrentWeek(expense.date));
	};

	const weekEntries = getCurrentWeekEntries();
	const weekTipExpenses = getCurrentWeekTipExpenses();
	const betsThisWeek = weekEntries.length;
	const profitThisWeek = weekEntries.reduce(
		(sum, entry) => sum + entry.net,
		0
	);
	const loggedTipsThisWeek = weekTipExpenses.reduce(
		(sum, expense) => sum + expense.amount,
		0
	);
	
	// For weekly packages, the tip is pre-paid at the start of the week
	// So we treat the full weekly package price as "spent" (it's a sunk cost)
	const tipsSpentThisWeek = settings.tipPricingType === 'weekly'
		? Math.max(loggedTipsThisWeek, settings.weeklyPackagePrice)
		: loggedTipsThisWeek;

	// Calculate this week's actual wins and losses
	const winsThisWeek = weekEntries.filter((entry) => entry.net > 0).length;
	const lossesThisWeek = weekEntries.filter((entry) => entry.net < 0).length;
	const totalLossAmount = weekEntries
		.filter((entry) => entry.net < 0)
		.reduce((sum, entry) => sum + Math.abs(entry.net), 0);

	// Check if first entry ever is in this week (to match how Stats Strip calculates currentBalance)
	const sortedEntries = [...entries].sort(
		(a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
	);
	const firstEntry = sortedEntries[0];
	const isFirstEntryInWeek = firstEntry && isInCurrentWeek(firstEntry.date);

	const calculateRequiredProfitPerBet = () => {
		const {
			weeklyProfitGoal,
			tipPricingType,
			weeklyPackagePrice,
			perBetTipPrice,
			estimatedBetsPerWeek,
		} = settings;

		let totalTipCost = 0;
		if (tipPricingType === 'weekly') {
			totalTipCost = weeklyPackagePrice;
		} else {
			totalTipCost = perBetTipPrice * estimatedBetsPerWeek;
		}

		const totalNeeded = weeklyProfitGoal + totalTipCost;
		const profitPerBet = totalNeeded / estimatedBetsPerWeek;

		return {
			totalNeeded,
			totalTipCost,
			profitPerBet,
		};
	};

	const calculateAdjustedRequired = () => {
		const {
			weeklyProfitGoal,
			tipPricingType,
			weeklyPackagePrice,
			perBetTipPrice,
			estimatedBetsPerWeek,
		} = settings;

		let totalTipCostExpected = 0;
		if (tipPricingType === 'weekly') {
			totalTipCostExpected = weeklyPackagePrice;
		} else {
			totalTipCostExpected = perBetTipPrice * estimatedBetsPerWeek;
		}

		const remainingBets = Math.max(0, estimatedBetsPerWeek - betsThisWeek);

		// Calculate Net After Tips to match Stats Strip's True Profit After Tips
		// When first entry is in current week, include baseline as starting point (like currentBalance does)
		// This makes calculator match stats when all data is from current week
		const weeklyBalance =
			(isFirstEntryInWeek ? baseline ?? 0 : 0) + profitThisWeek;
		const trueNetAfterTips = weeklyBalance - tipsSpentThisWeek;

		if (remainingBets === 0) {
			return {
				remainingBets: 0,
				profitNeeded: 0,
				requiredPerBet: 0,
				netAfterTips: trueNetAfterTips,
				shortfall: weeklyProfitGoal - trueNetAfterTips,
				remainingTipCost: 0,
				totalStillNeeded: 0,
			};
		}

		const netProfitSoFar = trueNetAfterTips;
		const remainingToGoal = weeklyProfitGoal - netProfitSoFar;

		let remainingTipCost = 0;
		if (tipPricingType === 'weekly') {
			remainingTipCost =
				tipsSpentThisWeek >= weeklyPackagePrice
					? 0
					: weeklyPackagePrice - tipsSpentThisWeek;
		} else {
			remainingTipCost = perBetTipPrice * remainingBets;
		}

		const totalStillNeeded = remainingToGoal + remainingTipCost;
		const requiredPerBet = totalStillNeeded / remainingBets;

		return {
			remainingBets,
			profitNeeded: totalStillNeeded,
			requiredPerBet,
			netAfterTips: netProfitSoFar,
			shortfall: remainingToGoal,
			remainingTipCost,
			totalStillNeeded,
		};
	};

	const baselineCalc = calculateRequiredProfitPerBet();
	const adjusted = calculateAdjustedRequired();

	// Calculate bet amount needed based on profit % per win
	// Simple formula: Bet Amount = Required Profit / (Profit % / 100)
	const profitPercentDecimal = settings.profitPercentPerWin / 100;
	const baselineBetAmount =
		profitPercentDecimal > 0
			? baselineCalc.profitPerBet / profitPercentDecimal
			: 0;
	const adjustedBetAmount =
		profitPercentDecimal > 0 && adjusted.remainingBets > 0
			? adjusted.requiredPerBet / profitPercentDecimal
			: 0;

	return (
		<Card className='p-4 sm:p-6 space-y-4'>
			<div className='flex items-center gap-2 mb-4'>
				<Calculator className='w-5 h-5 text-primary' />
				<h2 className='text-lg font-semibold'>Profit Calculator</h2>
			</div>

			<div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
				<div className='space-y-4'>
					<div>
						<Label htmlFor='weekStart' className='text-sm'>
							Week Start Date
						</Label>
						<Input
							id='weekStart'
							type='date'
							value={settings.weekStartDate}
							onChange={(e) =>
								setSettings({
									...settings,
									weekStartDate: e.target.value,
								})
							}
							data-testid='input-week-start'
							className='mt-1'
						/>
						<p className='text-xs text-muted-foreground mt-1'>
							Set when you purchased your weekly package or when
							your week starts
						</p>
					</div>

					<div>
						<Label htmlFor='weeklyGoal' className='text-sm'>
							Weekly Profit Goal ($)
						</Label>
						<Input
							id='weeklyGoal'
							type='number'
							value={settings.weeklyProfitGoal}
							onChange={(e) =>
								setSettings({
									...settings,
									weeklyProfitGoal:
										parseFloat(e.target.value) || 0,
								})
							}
							data-testid='input-weekly-goal'
							className='mt-1'
						/>
					</div>

					<div>
						<Label htmlFor='tipType' className='text-sm'>
							Tip Pricing Type
						</Label>
						<Select
							value={settings.tipPricingType}
							onValueChange={(value: 'weekly' | 'per-bet') =>
								setSettings({
									...settings,
									tipPricingType: value,
								})
							}>
							<SelectTrigger
								id='tipType'
								data-testid='select-tip-type'
								className='mt-1'>
								<SelectValue />
							</SelectTrigger>
							<SelectContent>
								<SelectItem value='weekly'>
									Weekly Package
								</SelectItem>
								<SelectItem value='per-bet'>
									Per-Bet Tip
								</SelectItem>
							</SelectContent>
						</Select>
					</div>

					{settings.tipPricingType === 'weekly' ? (
						<div>
							<Label htmlFor='weeklyPackage' className='text-sm'>
								Weekly Package Price ($)
							</Label>
							<Input
								id='weeklyPackage'
								type='number'
								value={settings.weeklyPackagePrice}
								onChange={(e) =>
									setSettings({
										...settings,
										weeklyPackagePrice:
											parseFloat(e.target.value) || 0,
									})
								}
								data-testid='input-weekly-package'
								className='mt-1'
							/>
						</div>
					) : (
						<div>
							<Label htmlFor='perBetTip' className='text-sm'>
								Per-Bet Tip Price ($)
							</Label>
							<Input
								id='perBetTip'
								type='number'
								value={settings.perBetTipPrice}
								onChange={(e) =>
									setSettings({
										...settings,
										perBetTipPrice:
											parseFloat(e.target.value) || 0,
									})
								}
								data-testid='input-per-bet-tip'
								className='mt-1'
							/>
						</div>
					)}

					<div>
						<Label htmlFor='betsPerWeek' className='text-sm'>
							Estimated Bets Per Week
						</Label>
						<Input
							id='betsPerWeek'
							type='number'
							value={settings.estimatedBetsPerWeek}
							onChange={(e) =>
								setSettings({
									...settings,
									estimatedBetsPerWeek:
										parseInt(e.target.value) || 0,
								})
							}
							data-testid='input-bets-per-week'
							className='mt-1'
						/>
					</div>

					<div>
						<Label htmlFor='profitPercent' className='text-sm'>
							Profit % Per Win
						</Label>
						<Input
							id='profitPercent'
							type='number'
							step='0.1'
							value={settings.profitPercentPerWin}
							onChange={(e) =>
								setSettings({
									...settings,
									profitPercentPerWin:
										parseFloat(e.target.value) || 0,
								})
							}
							data-testid='input-profit-percent'
							className='mt-1'
						/>
						<p className='text-xs text-muted-foreground mt-1'>
							e.g., 90.9 for -110 odds, 100 for +100 odds
						</p>
					</div>
				</div>

				<div className='space-y-4'>
					<Card className='p-4 bg-muted/50'>
						<h3 className='text-sm font-semibold mb-3 flex items-center gap-2'>
							<Calculator className='w-4 h-4' />
							Baseline Calculation
						</h3>
						<div className='space-y-2 text-sm'>
							<div className='flex justify-between'>
								<span className='text-muted-foreground'>
									Weekly Goal:
								</span>
								<span className='font-mono'>
									$
									{settings.weeklyProfitGoal.toLocaleString()}
								</span>
							</div>
							<div className='flex justify-between'>
								<span className='text-muted-foreground'>
									Tip Costs:
								</span>
								<span className='font-mono text-destructive'>
									-$
									{baselineCalc.totalTipCost.toLocaleString()}
								</span>
							</div>
							<div className='flex justify-between border-t pt-2'>
								<span className='text-muted-foreground'>
									Total Needed:
								</span>
								<span className='font-mono font-bold'>
									${baselineCalc.totalNeeded.toLocaleString()}
								</span>
							</div>
							<div className='flex justify-between pt-1'>
								<span className='text-muted-foreground'>
									Profit Per Bet:
								</span>
								<span
									className='font-mono font-bold'
									data-testid='text-baseline-per-bet'>
									${baselineCalc.profitPerBet.toFixed(2)}
								</span>
							</div>
							<div className='flex justify-between pt-1 bg-primary/10 -mx-2 px-2 py-2 rounded'>
								<span className='font-semibold'>
									Bet Amount:
								</span>
								<span
									className='font-mono font-bold text-primary'
									data-testid='text-baseline-bet'>
									${baselineBetAmount.toFixed(2)}
								</span>
							</div>
						</div>
					</Card>

					<Card
						className={`p-4 ${
							adjusted.shortfall > 0
								? 'bg-loss/10 border-loss'
								: 'bg-profit/10 border-profit'
						}`}>
						<h3 className='text-sm font-semibold mb-3 flex items-center gap-2'>
							{adjusted.shortfall > 0 ? (
								<AlertCircle className='w-4 h-4 text-loss' />
							) : (
								<TrendingUp className='w-4 h-4 text-profit' />
							)}
							This Week (Adjusted)
						</h3>
						<div className='space-y-2 text-sm'>
							<div className='flex justify-between'>
								<span className='text-muted-foreground'>
									Bets Made:
								</span>
								<span className='font-mono'>
									{betsThisWeek} /{' '}
									{settings.estimatedBetsPerWeek}
									{betsThisWeek > 0 && (
										<span className='ml-2 text-xs'>
											(
											<span className='text-profit'>
												{winsThisWeek}W
											</span>
											{lossesThisWeek > 0 && (
												<span className='text-loss'>
													{' '}
													/ {lossesThisWeek}L
												</span>
											)}
											)
										</span>
									)}
								</span>
							</div>
							<div className='flex justify-between'>
								<span className='text-muted-foreground'>
									Profit So Far:
								</span>
								<span
									className={`font-mono ${
										profitThisWeek >= 0
											? 'text-profit'
											: 'text-loss'
									}`}>
									${profitThisWeek.toLocaleString()}
								</span>
							</div>
							{lossesThisWeek > 0 && (
								<div className='flex justify-between'>
									<span className='text-muted-foreground'>
										Losses to Recoup:
									</span>
									<span className='font-mono text-loss'>
										${totalLossAmount.toLocaleString()}
									</span>
								</div>
							)}
							<div className='flex justify-between'>
								<span className='text-muted-foreground'>
									{settings.tipPricingType === 'weekly'
										? 'Weekly Package (Pre-paid):'
										: 'Tips Spent:'}
								</span>
								<span className={`font-mono ${tipsSpentThisWeek > 0 ? 'text-destructive' : ''}`}>
									{tipsSpentThisWeek > 0 ? `-$${tipsSpentThisWeek.toLocaleString()}` : '$0'}
								</span>
							</div>
							<div className='flex justify-between border-t pt-2'>
								<span className='text-muted-foreground'>
									Net After Tips:
								</span>
								<span
									className={`font-mono font-bold ${
										adjusted.netAfterTips >= 0
											? 'text-profit'
											: 'text-loss'
									}`}>
									${adjusted.netAfterTips.toLocaleString()}
								</span>
							</div>
							{adjusted.remainingBets > 0 && (
								<>
									<div className='flex justify-between pt-1'>
										<span className='text-muted-foreground'>
											{adjusted.shortfall > 0
												? 'Profit Still Needed:'
												: 'Ahead of Goal:'}
										</span>
										<span
											className={`font-mono ${
												adjusted.shortfall > 0
													? 'text-loss'
													: 'text-profit'
											}`}>
											{adjusted.shortfall > 0
												? `$${adjusted.shortfall.toLocaleString()}`
												: `OVER $${Math.abs(
														adjusted.shortfall
												  ).toLocaleString()}`}
										</span>
									</div>
									{adjusted.remainingTipCost > 0 && (
										<div className='flex justify-between'>
											<span className='text-muted-foreground'>
												{adjusted.shortfall <= 0
													? 'Tips Still to Cover:'
													: '+ Tips to Recoup:'}
											</span>
											<span
												className={`font-mono ${
													adjusted.shortfall <= 0
														? 'text-muted-foreground'
														: 'text-loss'
												}`}>
												$
												{adjusted.remainingTipCost.toLocaleString()}
											</span>
										</div>
									)}
									{adjusted.totalStillNeeded > 0 ? (
										<>
											<div className='flex justify-between border-t pt-1 mt-1'>
												<span className='text-muted-foreground font-semibold'>
													{adjusted.shortfall <= 0
														? 'Remaining for Tips:'
														: 'Total Still Needed:'}
												</span>
												<span
													className={`font-mono font-bold ${
														adjusted.shortfall <= 0
															? 'text-muted-foreground'
															: 'text-loss'
													}`}>
													$
													{adjusted.totalStillNeeded.toLocaleString()}
												</span>
											</div>
											<div className='flex justify-between pt-2'>
												<span className='text-muted-foreground'>
													Remaining Bets:
												</span>
												<span className='font-mono'>
													{adjusted.remainingBets}
												</span>
											</div>
											<div className='flex justify-between'>
												<span className='text-muted-foreground'>
													{adjusted.shortfall <= 0
														? 'Suggested Per Bet:'
														: 'Required Per Bet:'}
												</span>
												<span
													className={`font-mono font-bold ${
														adjusted.shortfall <= 0
															? 'text-profit'
															: adjusted.requiredPerBet >
															  baselineCalc.profitPerBet
															? 'text-loss'
															: 'text-profit'
													}`}
													data-testid='text-adjusted-per-bet'>
													$
													{adjusted.requiredPerBet.toFixed(
														2
													)}
												</span>
											</div>
											<div className='flex justify-between pt-1 bg-background/50 -mx-2 px-2 py-2 rounded'>
												<span className='font-semibold'>
													{adjusted.shortfall <= 0
														? 'Suggested Bet Amount:'
														: 'Bet Amount Needed:'}
												</span>
												<span
													className={`font-mono font-bold ${
														adjusted.shortfall <= 0
															? 'text-profit'
															: adjustedBetAmount >
															  baselineBetAmount
															? 'text-loss'
															: 'text-profit'
													}`}
													data-testid='text-adjusted-bet'>
													$
													{adjustedBetAmount.toFixed(
														2
													)}
												</span>
											</div>
											{adjusted.shortfall <= 0 ? (
												<p className='text-xs text-muted-foreground mt-2'>
													🎉 You've hit your profit
													goal! This is just to cover
													remaining tip costs.
												</p>
											) : (
												adjustedBetAmount >
													baselineBetAmount && (
													<p className='text-xs text-muted-foreground mt-2'>
														Bet amount increased to
														recover from
														{totalLossAmount > 0 &&
															` $${totalLossAmount.toLocaleString()} in losses`}
														{totalLossAmount > 0 &&
															adjusted.remainingTipCost >
																0 &&
															' and'}
														{adjusted.remainingTipCost >
															0 &&
															` $${adjusted.remainingTipCost.toLocaleString()} in tips`}
														.
													</p>
												)
											)}
										</>
									) : (
										<div className='pt-2 text-center border-t mt-2'>
											<p className='font-semibold text-profit'>
												🎉 Goal achieved! No more bets
												needed this week.
											</p>
										</div>
									)}
								</>
							)}
							{adjusted.remainingBets === 0 && (
								<div className='pt-2 text-center'>
									<p
										className={`font-semibold ${
											adjusted.shortfall > 0
												? 'text-loss'
												: 'text-profit'
										}`}>
										{adjusted.shortfall > 0
											? `Goal missed by $${Math.abs(
													adjusted.shortfall
											  ).toLocaleString()}`
											: `Goal exceeded by $${Math.abs(
													adjusted.shortfall
											  ).toLocaleString()}`}
									</p>
								</div>
							)}
						</div>
					</Card>
				</div>
			</div>

			<div className='pt-2 border-t'>
				<p className='text-xs text-muted-foreground'>
					Week runs from{' '}
					{parseLocalDate(
						settings.weekStartDate
					).toLocaleDateString()}{' '}
					to{' '}
					{new Date(
						parseLocalDate(settings.weekStartDate).getTime() +
							6 * 24 * 60 * 60 * 1000
					).toLocaleDateString()}
					. Bet amount = Required Profit ÷ Profit%. Adjusts in
					real-time as you log bets.
				</p>
			</div>
		</Card>
	);
}
